"""Method catalogue and worksheet templates (Manual Part B). Served to the client via /api/meta/methods."""

SEV = ["A", "B", "C", "D", "E"]
LIK = [5, 4, 3, 2, 1]

METHODS = {
    "bowtie": {"name": "Bowtie analysis", "chapter": 6, "kind": "diagram", "template_version": "1.0",
               "summary": "Threats, top event, consequences and the barriers on every path."},
    "hazid": {"name": "HAZID", "chapter": 7, "kind": "worksheet", "template_version": "1.0",
              "summary": "Guideword-driven brainstorm of hazards for a change.",
              "guidewords": ["People", "Procedures", "Equipment / systems", "Airspace and aerodrome", "Traffic",
                             "Environment", "Interfaces", "Transition", "Organisation"],
              "columns": [["id", "ID", 70], ["guideword", "Guideword", 130, "guideword"], ["hazard", "Hazard", 220],
                          ["causes", "Cause(s)", 180], ["consequences", "Consequence", 180],
                          ["controls", "Existing controls", 180], ["severity", "S", 55, "severity"],
                          ["likelihood", "L", 55, "likelihood"], ["risk", "Risk", 70, "risk"],
                          ["actions", "Actions", 200], ["owner", "Owner", 110], ["detailed_method", "Needs method", 120, "method"]]},
    "hazop": {"name": "HAZOP", "chapter": 8, "kind": "worksheet", "template_version": "1.0",
              "summary": "Nodes × parameters × guidewords generate deviations.",
              "guidewords": ["No / Not", "More", "Less", "As well as", "Part of", "Reverse", "Other than",
                             "Early", "Late", "Before", "After"],
              "parameters": {"procedural": ["Action", "Timing", "Sequence", "Information", "Communication"],
                             "data-flow": ["Message", "Content", "Timing", "Destination", "Sequence"]},
              "columns": [["id", "ID", 70], ["node", "Node", 120], ["parameter", "Parameter", 110], ["guideword", "Guideword", 110],
                          ["deviation", "Deviation", 180], ["causes", "Possible causes", 180], ["consequences", "Consequences", 180],
                          ["safeguards", "Safeguards", 170], ["severity", "S", 55, "severity"], ["likelihood", "L", 55, "likelihood"],
                          ["risk", "Risk", 70, "risk"], ["recommendation", "Recommendation", 200], ["not_meaningful", "N/A", 60, "bool"]]},
    "jha": {"name": "JHA", "chapter": 9, "kind": "worksheet", "template_version": "1.0",
            "summary": "Job steps, hazards and controls by the hierarchy of controls.",
            "hierarchy": ["Elimination", "Substitution", "Engineering", "Administrative", "PPE"],
            "columns": [["id", "Step", 60], ["step", "Job step", 200], ["hazards", "Hazards", 200], ["controls", "Controls", 260],
                        ["hierarchy", "Control type", 130, "hierarchy"], ["responsible", "Responsible", 120]]},
    "fmea": {"name": "FMEA / FMECA", "chapter": 10, "kind": "worksheet", "template_version": "1.0",
             "summary": "Failure modes, effects, detection, RPN and criticality.",
             "columns": [["id", "ID", 60], ["item", "Item", 140], ["failure_mode", "Failure mode", 150], ["cause", "Cause", 130],
                         ["end_effect", "End effect on ATS", 180], ["detection_method", "Detection", 140],
                         ["compensation", "Compensation", 150], ["s", "S", 50, "int10"], ["o", "O", 50, "int10"],
                         ["d", "D", 50, "int10"], ["rpn", "RPN", 65, "computed"], ["rate", "λp (/h)", 80, "number"],
                         ["alpha", "α", 55, "number"], ["beta", "β", 55, "number"], ["time", "t (h)", 65, "number"]]},
    "lopa": {"name": "LOPA", "chapter": 11, "kind": "calculator", "template_version": "1.0",
             "summary": "Initiating event × modifiers × independent protection layers vs target."},
    "fha": {"name": "FHA", "chapter": 12, "kind": "worksheet", "template_version": "1.0",
            "summary": "Functions, failure conditions, effects, severity and safety objectives.",
            "failure_types": ["Total loss", "Partial loss / degradation", "Erroneous (detected)", "Erroneous (undetected)",
                              "Unintended", "Delayed"],
            "columns": [["id", "ID", 60], ["function", "Function", 170], ["failure_type", "Failure type", 150, "failure_type"],
                        ["condition", "Failure condition", 200], ["effect", "Operational effect", 240],
                        ["severity", "Severity", 70, "severity"], ["objective", "Safety objective (/op h)", 150, "computed"],
                        ["requirements", "Derived requirements", 220]]},
    "stpa": {"name": "STPA", "chapter": 13, "kind": "composite", "template_version": "1.0",
             "summary": "Losses, hazards, control structure, unsafe control actions and loss scenarios.",
             "uca_types": ["Not providing causes hazard", "Providing causes hazard",
                           "Too early / too late / wrong order", "Stopped too soon / applied too long"],
             "scenario_types": ["Inadequate feedback", "Flawed process model", "Conflicting control",
                                "Component failure", "Control action not executed properly"]},
    "fta": {"name": "FTA", "chapter": 14, "kind": "diagram", "template_version": "1.0",
            "summary": "Top-down gates and basic events; cut sets, probability and importance."},
    "fatigue": {"name": "Fatigue modelling", "chapter": 15, "kind": "calculator", "template_version": "1.0",
                "summary": "Three-process model alertness and KSS across a roster."},
    "fram": {"name": "FRAM", "chapter": 16, "kind": "diagram", "template_version": "1.0",
             "summary": "Functions with six aspects, couplings and performance variability.",
             "aspects": ["Input", "Output", "Precondition", "Resource", "Control", "Time"],
             "function_types": ["Human", "Technological", "Organisational"],
             "timing": ["Too early", "On time", "Too late", "Not at all"],
             "precision": ["Precise", "Acceptable", "Imprecise"]},
    "bbn": {"name": "Bayesian belief network", "chapter": 17, "kind": "diagram", "template_version": "1.0",
            "summary": "Causal graph with probability tables; predictive and diagnostic queries."},

    # ---------------- added in v0.2 (Manual chapters 18–30)
    "crm": {"name": "Collision risk modelling", "chapter": 18, "kind": "calculator", "template_version": "1.0",
            "summary": "Reich model: vertical (RVSM) and lateral (route spacing) collision risk against the TLS."},
    "eta": {"name": "Event tree analysis", "chapter": 19, "kind": "diagram", "template_version": "1.0",
            "summary": "Initiating event → barrier successes/failures → outcome frequencies."},
    "hra": {"name": "Human reliability (HEART / CARA)", "chapter": 20, "kind": "calculator", "template_version": "1.0",
            "summary": "Human error probabilities from generic task types and error-producing conditions."},
    "orc": {"name": "Occurrence risk classification", "chapter": 21, "kind": "worksheet", "template_version": "1.0",
            "summary": "ARMS Event Risk Classification and EUROCONTROL RAT scoring of occurrences."},
    "gsn": {"name": "Safety case (GSN)", "chapter": 22, "kind": "diagram", "template_version": "1.0",
            "summary": "Goal Structuring Notation argument linking claims to ARAP evidence.",
            "node_types": ["goal", "strategy", "solution", "context", "assumption", "justification"]},
    "cca": {"name": "Common cause analysis", "chapter": 23, "kind": "composite", "template_version": "1.0",
            "summary": "Zonal safety analysis, particular risks analysis and common mode analysis.",
            "zsa_columns": [["id", "ID", 70], ["zone", "Zone / room / site", 150], ["equipment", "Equipment installed", 200],
                            ["concern", "Installation concern", 220], ["check", "Check / rule", 200], ["finding", "Finding", 200],
                            ["action", "Action", 180]],
            "pra_columns": [["id", "ID", 70], ["risk", "Particular risk", 140, "particular"], ["zones", "Zones affected", 150],
                            ["equipment", "Equipment affected", 200], ["redundancy_defeated", "Defeats redundancy?", 120, "bool"],
                            ["effect", "Effect on service", 200], ["severity", "S", 55, "severity"], ["mitigation", "Mitigation", 200],
                            ["action", "Action", 160]],
            "cma_columns": [["id", "ID", 70], ["claim", "Independence claim", 220], ["items", "Items claimed independent", 180],
                            ["source", "Common-mode source", 150, "cm_source"], ["analysis", "Analysis", 240],
                            ["independent", "Independent?", 110, "yesno"], ["action", "Action", 180]],
            "particular_risks": ["Fire", "Flood / water ingress", "Lightning", "Earthquake", "Volcanic ash", "Tropical storm / wind",
                                 "Power surge", "Loss of HVAC / overheating", "EMI / RF interference", "Rodent / animal damage",
                                 "Vehicle impact", "Cyber attack", "Industrial action"],
            "cm_sources": ["Design / specification", "Software", "Manufacture", "Installation", "Maintenance / testing",
                           "Operation / personnel", "Environment", "Shared utilities (power, HVAC, network)", "Location"]},
    "rbd": {"name": "RBD and Markov analysis", "chapter": 24, "kind": "calculator", "template_version": "1.0",
            "summary": "System availability from block diagrams; Markov models for repair, standby and switchover."},
    "swift": {"name": "SWIFT", "chapter": 25, "kind": "worksheet", "template_version": "1.0",
              "summary": "Structured What-If Technique for small and temporary changes.",
              "guidewords": ["People", "Procedures", "Equipment and utilities", "Information and communication", "Timing and sequence",
                             "Location and environment", "Quantity and demand", "External events", "Management and organisation"],
              "columns": [["id", "ID", 60], ["guideword", "Prompt category", 150, "guideword"], ["what_if", "What if …?", 240],
                          ["consequence", "Hazard / consequence", 220], ["safeguards", "Safeguards", 200],
                          ["severity", "S", 55, "severity"], ["likelihood", "L", 55, "likelihood"], ["risk", "Risk", 70, "risk"],
                          ["recommendation", "Recommendation", 220], ["owner", "Owner", 110]]},
    "hta": {"name": "Hierarchical task analysis", "chapter": 26, "kind": "diagram", "template_version": "1.0",
            "summary": "Goals, sub-tasks and plans; error modes and links to human reliability.",
            "error_modes": ["Action omitted", "Action too early / late", "Wrong action", "Action on wrong object", "Check omitted",
                            "Information not obtained", "Wrong information communicated", "Information not communicated"]},
    "sim": {"name": "Simulation (RTS / FTS)", "chapter": 27, "kind": "calculator", "template_version": "1.0",
            "summary": "Validation exercise plan and results: measures, criteria and statistics."},
    "sej": {"name": "Structured expert judgement", "chapter": 28, "kind": "calculator", "template_version": "1.0",
            "summary": "Cooke's classical model (calibration, information, weights) and Delphi rounds."},
    "sec": {"name": "Security risk assessment", "chapter": 29, "kind": "worksheet", "template_version": "1.0",
            "summary": "Asset–threat–vulnerability risk register with safety impact (ISO/IEC 27005, ED-205).",
            "threat_sources": ["External attacker", "Insider (malicious)", "Insider (accidental)", "Supplier / third party", "Physical intrusion"],
            "columns": [["id", "ID", 60], ["asset", "Asset", 160], ["threat", "Threat scenario", 220], ["source", "Threat source", 140, "threat_source"],
                        ["vulnerability", "Vulnerability", 200], ["c", "C", 50, "int5"], ["i", "I", 50, "int5"], ["a", "A", 50, "int5"],
                        ["likelihood", "L (1–5)", 70, "int5"], ["sec_risk", "Security risk", 110, "computed"],
                        ["controls", "Existing controls", 200], ["safety_severity", "Safety effect (S)", 110, "severity"],
                        ["treatment", "Treatment", 200], ["owner", "Owner", 110]]},
    "inv": {"name": "Occurrence investigation", "chapter": 30, "kind": "composite", "template_version": "1.0",
            "summary": "SOAM chart, HFACS classification and Tripod Beta; failed barriers linked to bowties.",
            "soam_barriers": ["Awareness", "Restriction", "Detection", "Control and recovery", "Protection and containment", "Escape and rescue"],
            "soam_contextual": ["Workplace conditions", "Organisational climate", "Attitudes and personality", "Human performance limitations",
                                "Physiological and emotional factors"],
            "soam_orgfactors": ["Training (TR)", "Workforce management (WM)", "Accountability (AC)", "Communication (CO)",
                                "Organisational culture (OC)", "Competing goals (CG)", "Policies and procedures (PP)",
                                "Maintenance management (MM)", "Equipment and infrastructure (EI)", "Risk management (RM)",
                                "Change management (CM)", "External environment (EE)"],
            "hfacs": {"Unsafe acts": ["Skill-based errors", "Decision errors", "Perceptual errors", "Routine violations", "Exceptional violations"],
                      "Preconditions for unsafe acts": ["Physical environment", "Technological environment", "Adverse mental states",
                                                        "Adverse physiological states", "Physical / mental limitations",
                                                        "Crew / team resource management", "Personal readiness"],
                      "Unsafe supervision": ["Inadequate supervision", "Planned inappropriate operations", "Failed to correct a known problem",
                                             "Supervisory violations"],
                      "Organisational influences": ["Resource management", "Organisational climate", "Organisational process"]},
            "tripod_brf": ["Design (DE)", "Hardware (HW)", "Maintenance management (MM)", "Housekeeping (HK)", "Error-enforcing conditions (EC)",
                           "Procedures (PR)", "Communication (CO)", "Organisation (OR)", "Training (TR)", "Incompatible goals (IG)", "Defences (DF)"]},
    "wildlife": {"name": "Wildlife strike risk (species)", "chapter": 31, "kind": "calculator", "template_version": "1.0",
                 "summary": "Species-by-species strike likelihood × severity matrix from strike data; profiles, surveys and attractants within 13 km.",
                 "land_uses": ["Grass (short after mowing)", "Cattle grazing", "Rice fields (sawah)", "Tambak (aquaculture)", "Wetland / river mouth",
                               "Roost / nesting colony", "Landfill", "Orchard (fruit)", "Food waste / market", "Standing water / drains", "Other"],
                 "mitigation_types": ["Habitat", "Dispersal", "Land use", "Detection", "ATS", "Reporting", "Exclusion"],
                 "circle_km": 13},
    "ies": {"name": "Investigation expert system (ORLIO)", "chapter": "App. E", "kind": "composite", "template_version": "1.0",
            "summary": "Search past ORLIO AcciMaps, rate the evidence, fuzzy inference per case, Bayesian network across the library and ranked clues for evidence collection."},
    "atsb": {"name": "Safety investigation analysis (ATSB)", "chapter": "App. F", "kind": "composite", "template_version": "1.0",
             "summary": "ATSB method: sequence of events, safety factors list, tests for existence, influence and importance, safety issues with risk analysis (AirNav 5×5 or ATSB 6×6), safety action and analysis review."},
    "orgmap": {"name": "Organisational function map", "chapter": "App. D", "kind": "worksheet", "template_version": "1.0",
               "summary": "Every safety-related function mapped from its current to its new owner, with competence, capacity, authority and handover checked.",
               "options": {"fn_category": ["SMS", "Operations", "Technical", "Training and competence", "Barrier owner", "Support"],
                           "competence": ["confirmed", "gap", "unknown"], "capacity": ["adequate", "stretched", "overloaded", "unknown"],
                           "authority": ["in place", "pending", "none", "unknown"], "handover": ["done", "planned", "not planned", "unknown"]},
               "columns": [["id", "ID", 70], ["function", "Safety-related function", 230], ["gap", "Gaps", 200, "computed"], ["category", "Category", 110, "fn_category"],
                           ["old_owner", "Current owner", 150], ["new_owner", "New owner", 150], ["competence", "Competence", 100, "competence"],
                           ["capacity", "Capacity", 100, "capacity"], ["authority", "Authority", 100, "authority"], ["handover", "Handover", 100, "handover"],
                           ["action", "Action / notes", 220]]},
    "spi": {"name": "SPI register", "chapter": 32, "kind": "worksheet", "template_version": "1.0",
            "summary": "Safety performance indicators with baseline, target, alert level, owner, current value and status.",
            "options": {"spi_type": ["leading", "lagging"], "rag": ["green", "amber", "red"],
                        "frequency": ["weekly", "monthly", "quarterly", "6-monthly", "per event"]},
            "columns": [["id", "ID", 70], ["indicator", "Indicator", 240], ["type", "Type", 90, "spi_type"], ["linked", "Barrier / hazard", 150],
                        ["baseline", "Baseline", 90], ["target", "Target (SPT)", 100], ["alert", "Alert level", 110], ["frequency", "Frequency", 100, "frequency"],
                        ["owner", "Owner", 130], ["current", "Current", 90], ["status", "Status", 90, "rag"], ["escalation", "Escalation when alert", 220]]},
}
