"""Method catalogue and worksheet templates (Manual Part B). Served to the client via /api/meta/methods."""

SEV = ["A", "B", "C", "D", "E"]
LIK = [5, 4, 3, 2, 1]

METHODS = {
    "bowtie": {"name": "Bowtie analysis", "chapter": 6, "kind": "diagram", "template_version": "1.0",
               "summary": "Threats, top event, consequences and the barriers on every path."},
    "hazid": {"name": "HAZID", "chapter": 7, "kind": "worksheet", "template_version": "1.0",
              "summary": "Guideword-driven brainstorm of hazards for a change.",
              "guidewords": ["People", "Procedures", "Equipment / systems", "Airspace and aerodrome", "Traffic",
                             "Environment", "Interfaces", "Transition", "Organisation"],
              "columns": [["id", "ID", 70], ["guideword", "Guideword", 130, "guideword"], ["hazard", "Hazard", 220],
                          ["causes", "Cause(s)", 180], ["consequences", "Consequence", 180],
                          ["controls", "Existing controls", 180], ["severity", "S", 55, "severity"],
                          ["likelihood", "L", 55, "likelihood"], ["risk", "Risk", 70, "risk"],
                          ["actions", "Actions", 200], ["owner", "Owner", 110], ["detailed_method", "Needs method", 120, "method"]]},
    "hazop": {"name": "HAZOP", "chapter": 8, "kind": "worksheet", "template_version": "1.0",
              "summary": "Nodes × parameters × guidewords generate deviations.",
              "guidewords": ["No / Not", "More", "Less", "As well as", "Part of", "Reverse", "Other than",
                             "Early", "Late", "Before", "After"],
              "parameters": {"procedural": ["Action", "Timing", "Sequence", "Information", "Communication"],
                             "data-flow": ["Message", "Content", "Timing", "Destination", "Sequence"]},
              "columns": [["id", "ID", 70], ["node", "Node", 120], ["parameter", "Parameter", 110], ["guideword", "Guideword", 110],
                          ["deviation", "Deviation", 180], ["causes", "Possible causes", 180], ["consequences", "Consequences", 180],
                          ["safeguards", "Safeguards", 170], ["severity", "S", 55, "severity"], ["likelihood", "L", 55, "likelihood"],
                          ["risk", "Risk", 70, "risk"], ["recommendation", "Recommendation", 200], ["not_meaningful", "N/A", 60, "bool"]]},
    "jha": {"name": "JHA", "chapter": 9, "kind": "worksheet", "template_version": "1.0",
            "summary": "Job steps, hazards and controls by the hierarchy of controls.",
            "hierarchy": ["Elimination", "Substitution", "Engineering", "Administrative", "PPE"],
            "columns": [["id", "Step", 60], ["step", "Job step", 200], ["hazards", "Hazards", 200], ["controls", "Controls", 260],
                        ["hierarchy", "Control type", 130, "hierarchy"], ["responsible", "Responsible", 120]]},
    "fmea": {"name": "FMEA / FMECA", "chapter": 10, "kind": "worksheet", "template_version": "1.0",
             "summary": "Failure modes, effects, detection, RPN and criticality.",
             "columns": [["id", "ID", 60], ["item", "Item", 140], ["failure_mode", "Failure mode", 150], ["cause", "Cause", 130],
                         ["end_effect", "End effect on ATS", 180], ["detection_method", "Detection", 140],
                         ["compensation", "Compensation", 150], ["s", "S", 50, "int10"], ["o", "O", 50, "int10"],
                         ["d", "D", 50, "int10"], ["rpn", "RPN", 65, "computed"], ["rate", "λp (/h)", 80, "number"],
                         ["alpha", "α", 55, "number"], ["beta", "β", 55, "number"], ["time", "t (h)", 65, "number"]]},
    "lopa": {"name": "LOPA", "chapter": 11, "kind": "calculator", "template_version": "1.0",
             "summary": "Initiating event × modifiers × independent protection layers vs target."},
    "fha": {"name": "FHA", "chapter": 12, "kind": "worksheet", "template_version": "1.0",
            "summary": "Functions, failure conditions, effects, severity and safety objectives.",
            "failure_types": ["Total loss", "Partial loss / degradation", "Erroneous (detected)", "Erroneous (undetected)",
                              "Unintended", "Delayed"],
            "columns": [["id", "ID", 60], ["function", "Function", 170], ["failure_type", "Failure type", 150, "failure_type"],
                        ["condition", "Failure condition", 200], ["effect", "Operational effect", 240],
                        ["severity", "Severity", 70, "severity"], ["objective", "Safety objective (/op h)", 150, "computed"],
                        ["requirements", "Derived requirements", 220]]},
    "stpa": {"name": "STPA", "chapter": 13, "kind": "composite", "template_version": "1.0",
             "summary": "Losses, hazards, control structure, unsafe control actions and loss scenarios.",
             "uca_types": ["Not providing causes hazard", "Providing causes hazard",
                           "Too early / too late / wrong order", "Stopped too soon / applied too long"],
             "scenario_types": ["Inadequate feedback", "Flawed process model", "Conflicting control",
                                "Component failure", "Control action not executed properly"]},
    "fta": {"name": "FTA", "chapter": 14, "kind": "diagram", "template_version": "1.0",
            "summary": "Top-down gates and basic events; cut sets, probability and importance."},
    "fatigue": {"name": "Fatigue modelling", "chapter": 15, "kind": "calculator", "template_version": "1.0",
                "summary": "Three-process model alertness and KSS across a roster."},
    "fram": {"name": "FRAM", "chapter": 16, "kind": "diagram", "template_version": "1.0",
             "summary": "Functions with six aspects, couplings and performance variability.",
             "aspects": ["Input", "Output", "Precondition", "Resource", "Control", "Time"],
             "function_types": ["Human", "Technological", "Organisational"],
             "timing": ["Too early", "On time", "Too late", "Not at all"],
             "precision": ["Precise", "Acceptable", "Imprecise"]},
    "bbn": {"name": "Bayesian belief network", "chapter": 17, "kind": "diagram", "template_version": "1.0",
            "summary": "Causal graph with probability tables; predictive and diagnostic queries."},
}
